name: 'build'

on:
  pull_request:
  push:
#  schedule:
#    - cron: '0 0 * * 5'
  workflow_dispatch:
  repository_dispatch:
    types: [ build ]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      key: build
      skip-release: ${{ github.event_name == 'pull_request' }}
    secrets:
      gcr_token: '${{ secrets.GCR_JSON_KEY }}'
      gh_token: '${{ github.token }}'
      docker_user: '${{ secrets.DOCKER_USER }}'
      docker_pass: '${{ secrets.DOCKER_PASS }}'
