name: 'a1'

on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:
  repository_dispatch:
    types: [ a1 ]

env:
  DOCKER_BUILDKIT: 1

jobs:
  a1:
    uses: ./.github/workflows/common.yml
    with:
      key: a1
      skip-release: ${{ github.event_name == 'pull_request' }}
    secrets:
      gcr_token: '${{ secrets.GCR_JSON_KEY }}'
      gh_token: '${{ github.token }}'
      docker_user: '${{ secrets.DOCKER_USER }}'
      docker_pass: '${{ secrets.DOCKER_PASS }}'
