name: Build
on:
  workflow_call:
    inputs:
      my_var:
        description: 'My VAR'
        required: false
        type: string
    secrets: 
      token:
        description: 'A required token from secrets'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Cache........'
      - run: echo 'Checkout.....'
      - run: echo 'Building.....'
      - run: echo 'after script if master'
      - run: echo $my_var
      - run: echo $token
      - run: echo $main1
      - run: echo ${{ secrets.token }}