name: Deploy DEV - Pull Request to development

on:
  pull_request:
    branches:
    - development
    paths-ignore:
    - 'README.md'

# Environment variables available to all jobs and steps in this workflow
env:
  PROJECT: medium
  GKE_ZONE: us-west2
  GKE_CLUSTER: meidum
  NAMESPACE: development
  ENV: dev
  #GITHUB_SHA: ${{ github.sha }}
  REGISTRY_HOSTNAME: gcr.io
  SERVICE_NAME: mediumpod

jobs:
  pull_request_workflow:
    name: Deploy DEV - Pull Request to development
    runs-on: ubuntu-18.04
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Dockerfile
    - name: Docker build
      run: |
        DOCKER_BUILDKIT=1 docker build \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          .
    # Lint
    - name: Lint
      run: |
        LINT
    # Unit Test
    - name: Unit Test
      run: |
        UNIT
