name: Java CI (development)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'jobs>build>steps>run'

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo 'jobs>test>steps>run'

  prep-releases:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo 'before call all dependencies matrix'
