name: Java CI (development)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'jobs>build>steps>run'
  build2:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'jobs>build2>steps>run'
  build3:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'jobs>build3>steps>run'
